apiVersion: v1
kind: Service
metadata:
  name: snapcrate-service
spec:
  type: LoadBalancer
  selector:
    app: snapcrate-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
